# Generated by Django 5.1 on 2024-08-22 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="name",
            field=models.FileField(upload_to="media"),
        ),
    ]
